{
 "title": "dashboard_test2",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory Usage [%]",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_used / 40000000", "legendFormat": "{{objectId}}" }
   ]
  },
  {
   "title": "CPU Usage [%]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "cpu_usage{}", "legendFormat": "{{objectId}}" }
   ]
  },
  {
   "title": "LSP BandWidth [kb/s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "irate(aggregate_octets[1m]) * 8 / 1000",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Active BGP Neighbors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(established_transitions == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inactive BGP Neighbors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(established_transitions == 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}