version: '0.2'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.cfg'
    networks:
      - backend  
    ports:
      - "9090:9090"
    restart: always  

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret  # Change this to your preferred admin password
    depends_on:
      - prometheus
    networks:
      - backend       
    ports:
      - "3000:3000"
    restart: always  

  kafka-prometheus-exporter:
    image: ghcr.io/cloud-native-everything/nsp-kafka-prometheus:v2311
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${NSP_BOOTSTRAP_SERVER:-10.2.16.11:9192}
      - CA_CERT_PATH=/app/${CA_KAFKA_CERT:-truststore.pem}
      - METRICS_PORT=8000
      - CONFIG_FILE=/app/metrics.yml
    volumes:
      - .:/app
    networks:
      - backend       
    ports:
      - "8000:8000"
    restart: always  

networks:
  backend:
