version: '0.1'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret  # Change this to your preferred admin password
    depends_on:
      - prometheus
    ports:
      - "3000:3000"

  kafka-prometheus-exporter:
    build: .
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=your_kafka_server:9092
      - CA_CERT_PATH=/app/truststore.pem
      - METRICS_PORT=8000
      - CONFIG_FILE=/app/config.yaml
    volumes:
      - ./truststore.pem:/app/truststore.pem
      - ./config.yaml:/app/config.yaml
    ports:
      - "8000:8000"


