{
 "title": "dashboard_test",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Transmitted Objects - Ports",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "transmitted_octets{job=\"nsp-kafka\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage [%]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "cpu_usage{}", "legendFormat": "{{objectId}}" }
   ]
  },
  {
   "title": "LSP BandWidth [Octets]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "targets": [
    { "expr": "irate(aggregate_octets[1m])", "legendFormat": "__auto" }
   ]
  }
 ]
}